version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # requirements.txt location
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    allow:
      - dependency-type: "direct"
    rebase-strategy: "auto"
