[tool.black]
line-length = 88
target_version = ['py312']

[tool.pyright]
typeCheckingMode = "basic"
include = ["."]
extraPaths = ["."]
reportAttributeAccessIssue = false

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
skip = [".venv", "ve"]
known_third_party = ["chess.pgn"]
